INSERT INTO
    Valoraciones (
        id_subasta,
        fachada_y_exteriores,
        techo_y_canaletas,
        ventanas_y_puerta,
        jardin_y_terrenos,
        estado_estructuras,
        instalaciones_visibles,
        vecindario,
        seguridad,
        ruido_y_olores,
        acceso_y_estacionamiento,
        localizacion,
        estado_inquilino,
        tipo_de_vivienda,
        puntuacion_final
    )
VALUES
    (
        (
            SELECT
                id_subasta
            FROM
                Subastas
            WHERE
                direccion = 'CL ANCORA 4 N2-8 Es:1 Pl:01 Pt:G EDIFICIO ANCORA 1ª FASE'
        ),
        10,
        10,
        8,
        10,
        9,
        10,
        9,
        9,
        9,
        7,
        9,
        3,
        10,
        8.58
    );