name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Despliega cuando se haga push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a v3 para usar Node.js 16 o superior

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Actualiza a la última versión compatible
        with:
          server: 45.84.205.143  # Usa solo la IP sin el prefijo ftp://
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Directorio de tu proyecto local
          server-dir: /public_html/  # Directorio en tu servidor
